name: Build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@master
      - name: Build Image & Push to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: andrewts129/festival-base-image
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
